<?php

namespace AppBundle\Repository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends \Doctrine\ORM\EntityRepository
{
//    public function getLocationsValid($status)
//    {
//        $query = $this->createQueryBuilder('loc')
//            ->where('loc.status == 1')
//            ->setParameters(
//                array(
//                    'status' => $status,
//
//                )
//            )
//            ->getQuery();
//        return $query->getResult();
//
//    }
}
